# .github/branch-protection.yml
name: Branch Protection Rules

rules:
  main:
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
      
      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts:
          - "SonarQube Code Analysis"
          - "OWASP ZAP Security Scan"
          - "Terraform Plan"
          - "Infrastructure Validation"
          - "Security Policy Compliance"
      
      # Additional protection rules
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      
      # Restrict who can push to the protected branch
      restrictions:
        users: []
        teams: ["devops-team", "security-team"]
        apps: []

  # Development branch protections
  develop:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      
      required_status_checks:
        strict: true
        contexts:
          - "SonarQube Code Analysis"
          - "Infrastructure Validation"