apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = grafana.monitoring.svc.cluster.local
    root_url = %(protocol)s://%(domain)s/
