apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-gatekeeper-app
  namespace: argocd
spec:
  destination:
    namespace: opa-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
    targetRevision: main
    path: infrastructure/kubernetes/opa-gatekeeper
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "-1"  # Ensures OPA deploys before workloads
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies-app
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
    targetRevision: main
    path: infrastructure/kubernetes/network-policies
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "0"  # Deploys right after OPA
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-namespace-app
  namespace: argocd
spec:
  destination:
    namespace: non-privileged-namespace
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
    targetRevision: main
    path: infrastructure/kubernetes/security-namespace
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "1"  # Deploys after OPA & Network Policies
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-app
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
    targetRevision: main
    path: infrastructure/kubernetes/istio
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "2"  # Deploys after Security Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-app
  namespace: argocd
spec:
  destination:
    namespace: privileged-namespace
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
    targetRevision: main
    path: infrastructure/kubernetes/falco
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "3"  # Deploys last to ensure monitoring is active
